services:
  postgres:
    image: postgis/postgis:latest
    platform: linux/amd64
    container_name: postgres-container
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "0.0.0.0:${POSTGRES_PORT}:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    ports:
      - "127.0.0.1:${CLICKHOUSE_PORT}:8123"
    volumes:
      - clickhouse-data:/var/lib/clickhouse
      - clickhouse-config:/etc/clickhouse-server
    environment:
      - CLICKHOUSE_DB=${CLICKHOUSE_DB}
      - CLICKHOUSE_USER=${CLICKHOUSE_USER:-default}     
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD:-my_secret_password}
      - CLICKHOUSE_DEFAULT_USER=${CLICKHOUSE_USER:-default}

  airflow-postgres:
    image: postgres:latest
    container_name: airflow-postgres
    environment:
      POSTGRES_USER: airflow_user
      POSTGRES_PASSWORD: airflow_password
      POSTGRES_DB: airflow_db
    ports:
      - "127.0.0.1:5433:5432"
    volumes:
      - airflow_pg_data:/var/lib/postgresql/data

  airflow:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    image: custom_airflow:latest
    container_name: airflow
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow_user:airflow_password@airflow-postgres:5432/airflow_db
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    ports:
      - "127.0.0.1:8080:8080"
    env_file:
      - .env
    volumes:
      - ./dags:/opt/airflow/dags
      - ./src:/opt/airflow/dags/src
    depends_on:
      - airflow-postgres
    command: >
      bash -c "
      rm -f /opt/airflow/airflow-webserver.pid && \
      airflow db init && \
      airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com && \
      airflow scheduler & \
      airflow webserver"

  superset:
    build:
      context: .
      dockerfile: Dockerfile.superset
    container_name: superset
    ports:
      - "8088:8088"
    environment:
      SUPERSET_SECRET_KEY: 'a_random_long_secret_key'
      DATABASE_URL: postgresql+psycopg2://superset:superset@superset_db:5432/superset
      REDIS_URL: redis://superset_redis:6379/0
    volumes:
      - superset_home:/app/superset_home
    depends_on:
      - superset_db
      - superset_redis
    restart: always
    command: >
      /bin/bash -c "
      superset db upgrade &&
      superset fab create-admin --username admin --firstname Superset --lastname Admin --email admin@superset.com --password admin &&
      superset init &&
      superset run -h 0.0.0.0 -p 8088"

  superset_db:
    image: postgres:15
    container_name: superset_db
    environment:
      POSTGRES_DB: superset
      POSTGRES_USER: superset
      POSTGRES_PASSWORD: superset
    volumes:
      - superset_db_data:/var/lib/postgresql/data

  superset_redis:
    image: redis:latest
    container_name: superset_redis
  

volumes:
  pg_data:
  logs:
  clickhouse-data:
  clickhouse-config:
  airflow_pg_data:
  superset_home:
  superset_db_data:
